apiVersion: v1
kind: ServiceAccount
metadata:
 name: curl-user
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  serviceAccountName: curl-user
  containers:
    - name: curl-container
      image: curlimages/curl
      command: ["sleep", "infinity"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
subjects:
- kind: ServiceAccount
  name: curl-user
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
